# NumPy

Start with installing the numpy library, in your terminal run `pip install numpy`

Once installed we can get started, 

we will import the library as np (This is the standard convention)

In [32]:
import numpy as np

## Arrays

Numpy arrays are similar to python lists, with key differences:
- NumPy arrays store elements of same(Homogeneous) datatype, list can store multiple data types

The NumPy array has benifts like:
- Numpy Arrays are more memory effiecient.
- They are much faster.
- Many buit-in funcitons. 
- They are desined to perform numerical operations on largedatasets.

In [33]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

## Basic NumPy Methods/APIs on Arrays

- Creating a 2d array

In [34]:
TwoD_array = np.array([[1, 2, 3], [4, 5, 6]])
TwoD_array  

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# Access any element in the array using its index.
TwoD_array[1][2]  # Accessing the third element of the second row

np.int64(6)

- Check data types

In [36]:
TwoD_array.dtype

dtype('int64')

- explicitly define the data type of array

In [37]:
newArr = np.array([1, 2, 3], dtype=np.float64)

- Find length/size of array

In [38]:
newArr.size

3

- Get rows and columns i.e shape


In [39]:
TwoD_array.shape

(2, 3)

- Sort an array 

In [ ]:
TwoD_array.sort() # Axis is by default 1, so it sorts the array row wise
TwoD_array.sort(axis=0) # sorting the array column wise

# The above is used for in-place sorting.

# We can use np.sort() to return sorted array without modifying the original array.
np.sort(TwoD_array, axis=1) # sorting row wise
np.sort(TwoD_array, axis=0) # sorting column wise

np.sort(TwoD_array, axis=None) # sorting the entire array as if it were a 1D array

array([1, 2, 3, 4, 5, 6])

- Initialize a new array with zeros

In [41]:
np.zeros(5) # Creates a 1D array of zeros with 5 elements
np.zeros((2, 3)) # Creates a 2D array of zeros with 2 rows and 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

- Intialize new array with ones 

In [42]:
np.ones(4) # Creates a 1D array of ones with 4 elements
np.ones((3, 2)) # Creates a 2D array of ones with 3 rows and 2 columns

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

- Initialize a new array with any value

In [43]:
np.full((2, 3), 7) # Creates a 2D array of shape (2, 3) filled with the value 7

array([[7, 7, 7],
       [7, 7, 7]])

- Some other methods to initialize

In [48]:
np.arange(0, 10) # Creates a 1D array with values from 0 to 9

np.arange(0, 10, 2) # Creates a 1D array with values from 0 to 9 with a step of 2

np.linspace(1, 5, 5) # Creates a 1D array with 5 evenly spaced values between 1 and 5

array([1., 2., 3., 4., 5.])

- Change the shape of an array

In [49]:
TwoD_array.reshape(3, 2) # Reshaping the array to have 3 rows and 2 columns

array([[1, 2],
       [3, 4],
       [5, 6]])

- Find min or max

In [ ]:
TwoD_array.min() # Returns the minimum value in the array
TwoD_array.max() # Returns the maximum value in the array

- Calculate Sum

In [ ]:
TwoD_array.sum() # Returns the sum of all elements in the array

np.int64(21)

In [51]:
TwoD_array.sum(axis=0) # Returns the sum of each column

array([5, 7, 9])

In [52]:
TwoD_array.sum(axis=1) # Returns the sum of each row

array([ 6, 15])

- Iterate through an array

In [53]:
for row in TwoD_array:
    print(row)

[1 2 3]
[4 5 6]


- Square of all elements on array

In [57]:
np.square(TwoD_array) # Returns the element-wise square of the array

array([[ 1,  4,  9],
       [16, 25, 36]])

- Square root of all element

In [58]:
np.sqrt(TwoD_array) # Returns the element-wise square root of the array

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

There are many more methods/api from numPy, look up docs for more

## Matrix Manipulation

A large amount of data we work with is in the form of tables i. e rows and cols, this is where matrix manipulation comes handy

In [ ]:
# Lets conside 2 2d arrays represention q1 and q1 sales of a company.

q1_sales = np.array([[100, 200, 300], [400, 500, 600]])

q2_sales = np.array([[150, 250, 350], [450, 550, 650]])

array([[ 250,  450,  650],
       [ 850, 1050, 1250]])

- Matrix addition

In [61]:
# We can perform element-wise addition to get the total sales for each quarter.
total_sales = q1_sales + q2_sales
total_sales

array([[ 250,  450,  650],
       [ 850, 1050, 1250]])