# NumPy

Start with installing the numpy library, in your terminal run `pip install numpy`

Once installed we can get started, 

we will import the library as np (This is the standard convention)

In [ ]:
import numpy as np

## Arrays

Numpy arrays are similar to python lists, with key differences:
- NumPy arrays store elements of same(Homogeneous) datatype, list can store multiple data types

The NumPy array has benifts like:
- Numpy Arrays are more memory effiecient.
- They are much faster.
- Many buit-in funcitons. 
- They are desined to perform numerical operations on largedatasets.

In [6]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

## Basic Operations on Arrays

- Creating a 2d array

In [12]:
TwoD_array = np.array([[1, 2, 3], [4, 5, 6]])
TwoD_array  

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# Access any element in the array using its index.
TwoD_array[1][2]  # Accessing the third element of the second row

np.int64(6)

- Check data types

In [13]:
TwoD_array.dtype

dtype('int64')

- explicitly define the data type of array

In [14]:
newArr = np.array([1, 2, 3], dtype=np.float64)

- Find length/size of array

In [23]:
newArr.size

3

- Get rows and columns i.e shape


In [18]:
TwoD_array.shape

(2, 3)

- Sort an array 

In [25]:
TwoD_array.sort() # Axis is by default 1, so it sorts the array row wise
TwoD_array.sort(axis=0) # sorting the array column wise

# The above is used for in-place sorting.

# We can use np.sort() to return sorted array without modifying the original array.
np.sort(TwoD_array, axis=1) # sorting row wise
np.sort(TwoD_array, axis=0) # sorting column wise

np.sort(TwoD_array, axis=None) # sorting the entire array as if it were a 1D array


array([1, 2, 3, 4, 5, 6])