# NumPy

Start with installing the numpy library, in your terminal run `pip install numpy`

Once installed we can get started, 

we will import the library as np (This is the standard convention)

In [32]:
import numpy as np

## Arrays

Numpy arrays are similar to python lists, with key differences:
- NumPy arrays store elements of same(Homogeneous) datatype, list can store multiple data types

The NumPy array has benifts like:
- Numpy Arrays are more memory effiecient.
- They are much faster.
- Many buit-in funcitons. 
- They are desined to perform numerical operations on largedatasets.

In [33]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

## Basic NumPy Methods/APIs on Arrays

- Creating a 2d array

In [34]:
TwoD_array = np.array([[1, 2, 3], [4, 5, 6]])
TwoD_array  

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# Access any element in the array using its index.
TwoD_array[1][2]  # Accessing the third element of the second row

np.int64(6)

- Check data types

In [36]:
TwoD_array.dtype

dtype('int64')

- explicitly define the data type of array

In [37]:
newArr = np.array([1, 2, 3], dtype=np.float64)

- Find length/size of array

In [38]:
newArr.size

3

- Get rows and columns i.e shape


In [39]:
TwoD_array.shape

(2, 3)

- Sort an array 

In [ ]:
TwoD_array.sort() # Axis is by default 1, so it sorts the array row wise
TwoD_array.sort(axis=0) # sorting the array column wise

# The above is used for in-place sorting.

# We can use np.sort() to return sorted array without modifying the original array.
np.sort(TwoD_array, axis=1) # sorting row wise
np.sort(TwoD_array, axis=0) # sorting column wise

np.sort(TwoD_array, axis=None) # sorting the entire array as if it were a 1D array

array([1, 2, 3, 4, 5, 6])

- Initialize a new array with zeros

In [41]:
np.zeros(5) # Creates a 1D array of zeros with 5 elements
np.zeros((2, 3)) # Creates a 2D array of zeros with 2 rows and 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

- Intialize new array with ones 

In [42]:
np.ones(4) # Creates a 1D array of ones with 4 elements
np.ones((3, 2)) # Creates a 2D array of ones with 3 rows and 2 columns

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

- Initialize a new array with any value

In [43]:
np.full((2, 3), 7) # Creates a 2D array of shape (2, 3) filled with the value 7

array([[7, 7, 7],
       [7, 7, 7]])

- Some other methods to initialize

In [48]:
np.arange(0, 10) # Creates a 1D array with values from 0 to 9

np.arange(0, 10, 2) # Creates a 1D array with values from 0 to 9 with a step of 2

np.linspace(1, 5, 5) # Creates a 1D array with 5 evenly spaced values between 1 and 5

array([1., 2., 3., 4., 5.])

- Change the shape of an array

In [49]:
TwoD_array.reshape(3, 2) # Reshaping the array to have 3 rows and 2 columns

array([[1, 2],
       [3, 4],
       [5, 6]])

- Find min or max

In [ ]:
TwoD_array.min() # Returns the minimum value in the array
TwoD_array.max() # Returns the maximum value in the array

- Find index of max or min

In [110]:
np.argmax(TwoD_array) # Returns the index of the maximum value in the array
np.argmin(TwoD_array) # Returns the index of the minimum value in the array

np.int64(0)

- Calculate Sum

In [ ]:
TwoD_array.sum() # Returns the sum of all elements in the array

np.int64(21)

In [51]:
TwoD_array.sum(axis=0) # Returns the sum of each column

array([5, 7, 9])

In [52]:
TwoD_array.sum(axis=1) # Returns the sum of each row

array([ 6, 15])

- Iterate through an array

In [53]:
for row in TwoD_array:
    print(row)

[1 2 3]
[4 5 6]


- Square of all elements on array

In [57]:
np.square(TwoD_array) # Returns the element-wise square of the array

array([[ 1,  4,  9],
       [16, 25, 36]])

- Square root of all element

In [58]:
np.sqrt(TwoD_array) # Returns the element-wise square root of the array

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

- Convert type 

In [112]:
TwoD_array[0].astype(np.float64) # Converts the first row of the array to float64 type

array([1., 2., 3.])

## Matrix Manipulation

A large amount of data we work with is in the form of tables i. e rows and cols, this is where matrix manipulation comes handy

In [ ]:
# Lets conside 2 2d arrays represention q1 and q1 sales of a company.

q1_sales = np.array([[100, 200, 300], [400, 500, 600]])

q2_sales = np.array([[150, 250, 350], [450, 550, 650]])

array([[ 250,  450,  650],
       [ 850, 1050, 1250]])

- Addition

In [61]:
# We can perform element-wise addition to get the total sales for each quarter.
total_sales = q1_sales + q2_sales
total_sales

array([[ 250,  450,  650],
       [ 850, 1050, 1250]])

- Difference or Substaction

In [63]:
# We can do subtraction to find the difference in sales between the two quarters.
sales_difference = q2_sales - q1_sales
sales_difference

array([[50, 50, 50],
       [50, 50, 50]])

In [66]:
# Let us now findout the percentage increase in sales from q1 to q2.
percentage_increase = ((q2_sales - q1_sales) * 100/ q1_sales)
percentage_increase

array([[50.        , 25.        , 16.66666667],
       [12.5       , 10.        ,  8.33333333]])

- Dot Product

In [69]:
np.dot(q1_sales, q2_sales.T) # Matrix multiplication of q1_sales and the transpose of q2_sales

array([[170000, 350000],
       [395000, 845000]])

- Cross Prduct

In [71]:
np.cross(q1_sales, q2_sales) # Cross product of q1_sales and q2_sales

array([[-5000, 10000, -5000],
       [-5000, 10000, -5000]])

## Slicing

In [72]:
arr = np.array([1, 2, 3, 4, 5])
arr[0:3] # Slicing the array to get the first three elements 
# 0 is the starting index (inclusive) and 3 is the ending index (exclusive)

array([1, 2, 3])

In [74]:
arr[2:5] # Slicing the array to get the last three elements

array([3, 4, 5])

In [75]:
arr[2:] # Slicing the array to get all elements from index 2 to the end

array([3, 4, 5])

In [76]:
arr[:3] # Slicing the array to get all elements from the beginning to index 2 (exclusive)

array([1, 2, 3])

In [77]:
arr[-1] # Accessing the last element of the array

np.int64(5)

In [78]:
b = np.array([[10, 20, 30],
              [1, 2, 3],
              [100, 200, 300]])

b[-1] # Accessing the last row of the array

array([100, 200, 300])

In [79]:
b[-1, 1:2] # Accessing the last row of and 2nd column of the array using slicing

array([200])

In [82]:
b[:, 2:3] # Accessing 3rd column of the array using slicing

array([[ 30],
       [  3],
       [300]])

## Stacking

Allows user to stick/concatenate/join 2 arrays

Lets take two 2d arrays a and b and `stack` them

In [85]:
a = np.array([[1, 2, 3],
             [11, 12, 13]])
a

array([[ 1,  2,  3],
       [11, 12, 13]])

In [87]:
b = np.array([[4, 5, 6],
              [14, 15, 16]])
b

array([[ 4,  5,  6],
       [14, 15, 16]])

In [91]:
np.hstack((a, b)) # Stacking arrays horizontally (column-wise)

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]])

In [93]:
np.vstack((a, b)) # Stacking arrays vertically (row-wise)

array([[ 1,  2,  3],
       [11, 12, 13],
       [ 4,  5,  6],
       [14, 15, 16]])

## Split

Similar to stacking we can also split/divide a array.

In [96]:
c = np.hstack((a, b)) # Stacking arrays horizontally (column-wise) and storing it in variable c
c

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]])

In [104]:
d, e = np.hsplit(c, [3]) # Splitting the array c into two arrays d and e at the 3rd column
print(d) # First two columns of c
print(e) # Last two columns of c

[[ 1  2  3]
 [11 12 13]]
[[ 4  5  6]
 [14 15 16]]


In [106]:
np.hsplit(c, 3) # Splitting the array c into three
 # using [] to specify index.

[array([[ 1,  2],
        [11, 12]]),
 array([[ 3,  4],
        [13, 14]]),
 array([[ 5,  6],
        [15, 16]])]

In [107]:
c

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]])

In [109]:
# We can also use np.vsplit() to split the array vertically (row-wise).
np.vsplit(c, 2) # Splitting the array c into two arrays vertically 
# use [] to specify index.

[array([[1, 2, 3, 4, 5, 6]]), array([[11, 12, 13, 14, 15, 16]])]

### There are many more methods, it is not recommended to memorize them. Learn as you go 